# Header
menu:
  首页: /
  随想: /1/thinkings
  存档: /1/archive
  关于: /1/about

# Content
excerpt_link: 阅读更多
content_max_width: 800px

# Sidebar
author:
  name: Nekoha Shizuku
  work: *
  location: Shanghai, China
  avatar_url: /images/avatar.jpg


#highlight:
#  enable: false
#prismjs:
#  enable: true
#  preprocess: true
#  line_number: true
#  tab_replace: ''
highlight:
  enable: true
  auto_detect: true
  line_number: true

#highlight:
#  enable: false
#  auto_detect: true
#  line_number: true
#  tab_replace: ''
#  wrap: true
#  hljs: true
#prismjs:
#  enable: true
#  preprocess: true
#  line_number: true
#  tab_replace: ''


#highlight:
#  enable: true
#  auto_detect: false
#  line_number: true
#  tab_replace: '  '
#  wrap: true
#  hljs: false
#prismjs:
#  enable: false
