# site name
prefixName: さくら荘その貓貓樂園
siteName:
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/avatar.jpg
url: https://littleneko.cf
description: 星火，日月，流年
cdn: http://rawcdn-git.littleneko.cf/
pjax: 1
# 1开启
mathjax: 1

notice: hexo Blog Debugging!
lazyloadImg: http://rawcdn-git.littleneko.cf/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: {
    技术: {path: /categories/技术/, fa: fa-code },
    生活: {path: /categories/生活/, fa: fa-file-text-o },
    资源: {path: /categories/资源/, fa: fa-cloud-download },
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
#    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce },
#    番组: {path: /bangumi/, fa: fa-film faa-vertical },
    歌单: {path: /music/, fa: fa-headphones },
#    图集: {path: /tags/图集/, fa: fa-photo }
  } }
#  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: {
    我？: {path: /about/, fa: fa-meetup},
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
#    Lab: {path: /lab/, fa: fa-cogs },
  } }
#  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
# 背景图片逻辑已修改，
bg:
  - https://img.2eka.cloud/api/random?type=pc

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-grid

# startdash url, title, desc img
startdash:
  - {url: https://t.me/momoesakura, title: Telegram, desc: 电报频道, img: /img/social/telegram.svg}
#  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
#  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 02/20/2021

#social  url, img PC端配置
social:
  github: {url: https://github.com/Nekoha-Shizuku, img: /img/social/github.png}
#  sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  telegram: {url: https://t.me/momoesakura, img: /img/social/telegram.svg}
#  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: mailto:moenachoneko2020@protonmail.com, img: /img/social/email.svg}
#  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
#  wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

# social  url, img 移动端配置
#msocial:
# github: {url: https://github.com/Nekoha-Shizuku, fa: fa-github, color: 333}
#  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
#  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}


# Lemon!
movies:
  url: https://gitee.com/c4e78670-7d9c-11eb-aafd/cdn0101/raw/master/
#  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: 109819229-1-208.mp4

#好耶,是Minecraft!
aplayer:
  id: 164521381
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: false
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

